# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/datapump

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/datapump

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/datapump/CMakeFiles /data/datapump/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/datapump/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named datapump

# Build rule for target.
datapump: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 datapump
.PHONY : datapump

# fast build rule for target.
datapump/fast:
	$(MAKE) -f CMakeFiles/datapump.dir/build.make CMakeFiles/datapump.dir/build
.PHONY : datapump/fast

datapump.o: datapump.c.o
.PHONY : datapump.o

# target to build an object file
datapump.c.o:
	$(MAKE) -f CMakeFiles/datapump.dir/build.make CMakeFiles/datapump.dir/datapump.c.o
.PHONY : datapump.c.o

datapump.i: datapump.c.i
.PHONY : datapump.i

# target to preprocess a source file
datapump.c.i:
	$(MAKE) -f CMakeFiles/datapump.dir/build.make CMakeFiles/datapump.dir/datapump.c.i
.PHONY : datapump.c.i

datapump.s: datapump.c.s
.PHONY : datapump.s

# target to generate assembly for a file
datapump.c.s:
	$(MAKE) -f CMakeFiles/datapump.dir/build.make CMakeFiles/datapump.dir/datapump.c.s
.PHONY : datapump.c.s

dir.o: dir.c.o
.PHONY : dir.o

# target to build an object file
dir.c.o:
	$(MAKE) -f CMakeFiles/datapump.dir/build.make CMakeFiles/datapump.dir/dir.c.o
.PHONY : dir.c.o

dir.i: dir.c.i
.PHONY : dir.i

# target to preprocess a source file
dir.c.i:
	$(MAKE) -f CMakeFiles/datapump.dir/build.make CMakeFiles/datapump.dir/dir.c.i
.PHONY : dir.c.i

dir.s: dir.c.s
.PHONY : dir.s

# target to generate assembly for a file
dir.c.s:
	$(MAKE) -f CMakeFiles/datapump.dir/build.make CMakeFiles/datapump.dir/dir.c.s
.PHONY : dir.c.s

mysqlconn.o: mysqlconn.c.o
.PHONY : mysqlconn.o

# target to build an object file
mysqlconn.c.o:
	$(MAKE) -f CMakeFiles/datapump.dir/build.make CMakeFiles/datapump.dir/mysqlconn.c.o
.PHONY : mysqlconn.c.o

mysqlconn.i: mysqlconn.c.i
.PHONY : mysqlconn.i

# target to preprocess a source file
mysqlconn.c.i:
	$(MAKE) -f CMakeFiles/datapump.dir/build.make CMakeFiles/datapump.dir/mysqlconn.c.i
.PHONY : mysqlconn.c.i

mysqlconn.s: mysqlconn.c.s
.PHONY : mysqlconn.s

# target to generate assembly for a file
mysqlconn.c.s:
	$(MAKE) -f CMakeFiles/datapump.dir/build.make CMakeFiles/datapump.dir/mysqlconn.c.s
.PHONY : mysqlconn.c.s

util.o: util.c.o
.PHONY : util.o

# target to build an object file
util.c.o:
	$(MAKE) -f CMakeFiles/datapump.dir/build.make CMakeFiles/datapump.dir/util.c.o
.PHONY : util.c.o

util.i: util.c.i
.PHONY : util.i

# target to preprocess a source file
util.c.i:
	$(MAKE) -f CMakeFiles/datapump.dir/build.make CMakeFiles/datapump.dir/util.c.i
.PHONY : util.c.i

util.s: util.c.s
.PHONY : util.s

# target to generate assembly for a file
util.c.s:
	$(MAKE) -f CMakeFiles/datapump.dir/build.make CMakeFiles/datapump.dir/util.c.s
.PHONY : util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... datapump"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... datapump.o"
	@echo "... datapump.i"
	@echo "... datapump.s"
	@echo "... dir.o"
	@echo "... dir.i"
	@echo "... dir.s"
	@echo "... mysqlconn.o"
	@echo "... mysqlconn.i"
	@echo "... mysqlconn.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

